import type { TemplateDefinition } from '@/domain/resume.types'

export const templateDefinitions: TemplateDefinition[] = [
  {
    id: 'clarity',
    name: 'Clarity',
    family: 'minimal',
    tags: ['Minimal', 'Modern'],
    theme: { accentColor: '#2563eb', fontFamily: 'sans' },
  },
  {
    id: 'meridian',
    name: 'Meridian',
    family: 'minimal',
    tags: ['Minimal', 'Modern'],
    theme: { accentColor: '#2f6b3a', fontFamily: 'sans' },
  },
  {
    id: 'aurora',
    name: 'Aurora',
    family: 'minimal',
    tags: ['Minimal', 'Modern'],
    theme: { accentColor: '#7c3aed', fontFamily: 'sans' },
  },
  {
    id: 'ember',
    name: 'Ember',
    family: 'minimal',
    tags: ['Minimal', 'Modern'],
    theme: { accentColor: '#c2410c', fontFamily: 'sans' },
  },
  {
    id: 'slate',
    name: 'Slate',
    family: 'minimal',
    tags: ['Minimal', 'Modern'],
    theme: { accentColor: '#475569', fontFamily: 'sans' },
  },

  {
    id: 'ledger',
    name: 'Ledger',
    family: 'sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#1f2937', secondaryColor: '#4b5768', fontFamily: 'sans' },
  },
  {
    id: 'northbound',
    name: 'Northbound',
    family: 'sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#0f6f66', secondaryColor: '#41a196', fontFamily: 'sans' },
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    family: 'sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#1e3a8a', secondaryColor: '#3b5bb0', fontFamily: 'sans' },
  },
  {
    id: 'maroon',
    name: 'Maroon',
    family: 'sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#7f1d1d', secondaryColor: '#a34444', fontFamily: 'sans' },
  },
  {
    id: 'ink',
    name: 'Ink',
    family: 'sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#111827', secondaryColor: '#4c3f8f', fontFamily: 'sans' },
  },

  {
    id: 'signal',
    name: 'Signal',
    family: 'bold-header',
    tags: ['Creative', 'Modern'],
    theme: { accentColor: '#db2777', fontFamily: 'sans' },
  },
  {
    id: 'confetti',
    name: 'Confetti',
    family: 'bold-header',
    tags: ['Creative', 'Modern'],
    theme: { accentColor: '#7c3aed', fontFamily: 'sans' },
  },
  {
    id: 'citrus',
    name: 'Citrus',
    family: 'bold-header',
    tags: ['Creative', 'Modern'],
    theme: { accentColor: '#ea580c', fontFamily: 'sans' },
  },
  {
    id: 'current',
    name: 'Current',
    family: 'bold-header',
    tags: ['Creative', 'Modern'],
    theme: { accentColor: '#2563eb', fontFamily: 'sans' },
  },
  {
    id: 'verdant',
    name: 'Verdant',
    family: 'bold-header',
    tags: ['Creative', 'Modern'],
    theme: { accentColor: '#16a34a', fontFamily: 'sans' },
  },

  {
    id: 'milestone',
    name: 'Milestone',
    family: 'timeline',
    tags: ['Timeline', 'Creative'],
    theme: { accentColor: '#b45309', fontFamily: 'serif' },
  },
  {
    id: 'waypoint',
    name: 'Waypoint',
    family: 'timeline',
    tags: ['Timeline', 'Creative'],
    theme: { accentColor: '#475569', fontFamily: 'serif' },
  },
  {
    id: 'heritage',
    name: 'Heritage',
    family: 'timeline',
    tags: ['Timeline', 'Creative'],
    theme: { accentColor: '#9f1239', fontFamily: 'serif' },
  },
  {
    id: 'voyage',
    name: 'Voyage',
    family: 'timeline',
    tags: ['Timeline', 'Creative'],
    theme: { accentColor: '#0f766e', fontFamily: 'serif' },
  },
  {
    id: 'legacy',
    name: 'Legacy',
    family: 'timeline',
    tags: ['Timeline', 'Creative'],
    theme: { accentColor: '#1e3a8a', fontFamily: 'serif' },
  },

  {
    id: 'plainscript',
    name: 'Plainscript',
    family: 'plain',
    tags: ['ATS-friendly', 'Minimal'],
    theme: { accentColor: '#111111', fontFamily: 'mono' },
  },
  {
    id: 'standard',
    name: 'Standard',
    family: 'plain',
    tags: ['ATS-friendly', 'Minimal'],
    theme: { accentColor: '#111111', fontFamily: 'sans' },
  },
  {
    id: 'ledgerline',
    name: 'Ledgerline',
    family: 'plain',
    tags: ['ATS-friendly', 'Minimal'],
    theme: { accentColor: '#374151', fontFamily: 'sans' },
  },
  {
    id: 'baseline',
    name: 'Baseline',
    family: 'plain',
    tags: ['ATS-friendly', 'Minimal'],
    theme: { accentColor: '#1d4ed8', fontFamily: 'sans' },
  },

  {
    id: 'portrait',
    name: 'Portrait',
    family: 'photo-sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#2b3648', secondaryColor: '#47536b', fontFamily: 'sans' },
  },
  {
    id: 'executive',
    name: 'Executive',
    family: 'photo-sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#1b2a41', secondaryColor: '#2f4770', fontFamily: 'sans' },
  },
  {
    id: 'harbor',
    name: 'Harbor',
    family: 'photo-sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#3c5068', secondaryColor: '#5c7694', fontFamily: 'sans' },
  },
  {
    id: 'summit',
    name: 'Summit',
    family: 'photo-sidebar',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#1f3a35', secondaryColor: '#2f5c53', fontFamily: 'sans' },
  },
  {
    id: 'onyx',
    name: 'Onyx',
    family: 'photo-sidebar',
    tags: ['Two-column', 'Creative'],
    theme: { accentColor: '#1c1c1f', secondaryColor: '#3f3f46', fontFamily: 'sans' },
  },

  {
    id: 'skyline',
    name: 'Skyline',
    family: 'banner-header',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#0f766e', fontFamily: 'sans' },
  },
  {
    id: 'azure',
    name: 'Azure',
    family: 'banner-header',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#1d4ed8', fontFamily: 'sans' },
  },
  {
    id: 'canopy',
    name: 'Canopy',
    family: 'banner-header',
    tags: ['Two-column', 'Modern'],
    theme: { accentColor: '#15803d', fontFamily: 'sans' },
  },
  {
    id: 'velvet',
    name: 'Velvet',
    family: 'banner-header',
    tags: ['Two-column', 'Creative'],
    theme: { accentColor: '#6d28d9', fontFamily: 'sans' },
  },
  {
    id: 'crimson',
    name: 'Crimson',
    family: 'banner-header',
    tags: ['Two-column', 'Creative'],
    theme: { accentColor: '#be123c', fontFamily: 'sans' },
  },
]
